"""
Danny Nguyen
A01353084
"""
import random
import tkinter as tk


def make_board(rows: int, columns: int) -> dict:
    """
    Make the board.

    A function that makes the board with name for each room in the board.

    :param rows: a positive integer
    :param columns: a positive integer
    :precondition: rows must be a positive integer greater than or equal to two
    :precondition: columns must be a positive integer greater than or equal to two
    :post-condition: define, make the board correctly, and randomly assign the name for each existed room
    :return: a dictionary that contains coordinates of the rooms in a tuple equivalent to the name of the room

    """
    rooms = ['Micetras', 'Lagormiths', 'Beanloo', 'Fobinicca', 'Rioncersu']
    return {(row, column): random.choice(rooms) for row in range(rows) for column in range(columns)}


def make_character() -> dict:
    """
    Make the character.

    A function that creates a character, with the starting coordinates and HP.

    :return: a dictionary that contains "X-coordinate" and "Y-coordinate" are equal to 0, "Current HP" is equal to 5

    >>> player = make_character()
    >>> player
    {'X-coordinate': 0, 'Y-coordinate': 0, 'Current HP': 5}

    >>> user = make_character()
    >>> user
    {'X-coordinate': 0, 'Y-coordinate': 0, 'Current HP': 5}

    """
    return {'X-coordinate': 0, 'Y-coordinate': 0, 'Current HP': 5}


def describe_current_location(board: dict, character: dict) -> None:
    """
    Describe current location.

    A function that tells which row and column the user at, with the name of the room and HP user has left.

    :param board: a dictionary
    :param character: a dictionary
    :precondition: board must be a dictionary that is created by make_board function
    :precondition: character must be a dictionary that is created by make_character function
    :post-condition: define and describe the row, colum, room, and HP level the character at

    """
    x_place = character["X-coordinate"]
    y_place = character["Y-coordinate"]
    hp = character["Current HP"]
    print(f"You're at row {y_place+1}, column {x_place+1}, The {board[(x_place, y_place)]}, with {hp} HP remaining.")


def get_user_choice() -> str:
    """
    Get user choice.

    A function that gets the user's choice for which direction they are moving next.
    :post-condition: define the valid keys and each move correctly
    :return: the direction user wants to move

    """
    while True:
        user_input = (input("Direction to move:\n1. [<] West\n2. [^] North\n3. [v] South\n4. [>] East\n")).lower()
        if user_input in ("north", "n", "south", "s", "east", "e", "west", "w", "1", "2", "3", "4"):
            break
        else:
            print(f"'{user_input}' is not defined as a valid key to move.\n")
    return user_input


def validate_move(character: dict, direction: str) -> bool:
    """
    Check if direction user want to go is valid.

    A function that checks if direction user wants to go is a valid move.

    :param character: a dictionary
    :param direction: a string
    :precondition: character must be created by make_character function
    :precondition: direction must be a string returned by get_user_choice function
    :post-condition: define a valid move correctly
    :return: a boolean: True if direction is a valid move; False if direction is not a valid move

    >>> valid_move_player = make_character()

    >>> first_direction = 'n'
    >>> validate_move(valid_move_player, first_direction)
    False

    >>> second_direction = 's'
    >>> validate_move(valid_move_player, second_direction)
    True

    >>> third_direction = 'w'
    >>> validate_move(valid_move_player, third_direction)
    False

    """
    if character["X-coordinate"] == 0 and direction in ("west", "w", "1"):
        return False
    elif character["X-coordinate"] == 4 and direction in ("east", "e", "4"):
        return False
    elif character["Y-coordinate"] == 0 and direction in ("north", "n", "2"):
        return False
    elif character["Y-coordinate"] == 4 and direction in ("south", "s", "3"):
        return False
    else:
        if direction in ("north", "n", "south", "s", "east", "e", "west", "w", "1", "2", "3", "4"):
            return True
        else:
            return False


def move_character(character: dict, direction: str) -> dict:
    """
    Move the character.

    A function that moves the character to the direction the user wants.

    :param character: a dictionary
    :param direction: a string
    :precondition: character must be a dictionary that is generated by make_character function
    :precondition: direction must be a string returned by get_user_choice function
    :post-condition: define and move the character's coordinates correctly
    :return: the new character dictionary after adjusting the character coordinates

    >>> player_move = make_character()
    >>> player_direction = "s"
    >>> after_player_move = move_character(player_move, player_direction)
    >>> after_player_move
    {'X-coordinate': 0, 'Y-coordinate': 1, 'Current HP': 5}

    >>> user_move = make_character()
    >>> user_direction = "e"
    >>> after_user_move = move_character(user_move, user_direction)
    >>> after_user_move
    {'X-coordinate': 1, 'Y-coordinate': 0, 'Current HP': 5}

    >>> tester_move = make_character()
    >>> tester_direction = "s"
    >>> later_tester_move = move_character(tester_move, tester_direction)
    >>> later_tester_move
    {'X-coordinate': 0, 'Y-coordinate': 1, 'Current HP': 5}

    """
    if direction in ("north", "n", "2"):
        character["Y-coordinate"] -= 1
    elif direction in ("south", "s", "3"):
        character["Y-coordinate"] += 1
    elif direction in ("east", "e", "4"):
        character["X-coordinate"] += 1
    elif direction in ("west", "w", "1"):
        character["X-coordinate"] -= 1
    return character


def check_if_goal_attained(character: dict) -> bool:
    """
    Check if goal attained.

    A function that checks if user reaches row 2 column 2.

    :param character: a dictionary
    :precondition: character must be a dictionary returned by make_character function
    :post-condition: define goal attained correctly
    :return: a boolean: True if goal attained; False if not

    >>> win_player = make_character()
    >>> win_player["X-coordinate"] = 4
    >>> win_player["Y-coordinate"] = 4
    >>> check_win = check_if_goal_attained(win_player)
    Congratulations! You reached your destination!
    >>> check_win
    True

    >>> not_win_player = make_character()
    >>> not_win_player["X-coordinate"] = 1
    >>> not_win_player["Y-coordinate"] = 2
    >>> check_not_win = check_if_goal_attained(not_win_player)
    >>> check_not_win
    False

    """
    if character["X-coordinate"] == 4 and character["Y-coordinate"] == 4:
        print(f"Congratulations! You reached your destination!")
        return True
    else:
        return False


def check_for_foes() -> bool:
    """
    Check for foes.

    A function that checks if foes is in the room or not.

    :post-condition: define and randomly assign foes
    :return: a boolean: True if there are foes; False if not

    """
    number = random.randint(1, 5)
    if number == 1:
        return True
    else:
        return False


def guessing_game(character: dict, upper: int) -> None:
    """
    A guessing game.

    A function that creates a game that requires user to guess a random number generated.

    :param character: a dictionary
    :param upper: an integer
    :precondition: character must be a dictionary that is returned by make_character function
    :precondition: upper must be a non-zero positive integer
    :post-condition: define and run the game correctly

    """
    secret_number = str(random.randint(1, upper))
    print("Opponents ahead! Guess the correct number to beat them.\n")
    if character["Current HP"] == 1:
        print("BE CAREFUL! If you guess this one wrong, you will lose the game!")
    guess = input(f"Enter a number from 1 to {upper}: ")
    if guess == secret_number:
        print(f"You're right! It's {guess}.\n")
    else:
        print(f"It's {secret_number}. You guessed it wrong! Losing 1 HP.\n")
        character["Current HP"] -= 1
        if character["Current HP"] == 1:
            print(f"WARNING: If you get one more wrong guess, you will lose the game! Be careful.\n")


def is_alive(character: dict) -> bool:
    """
    Check if the character is still alive.

    A function that checks if character is still alive or not.

    :param character: a dictionary
    :precondition: character must be a dictionary made from make_character function
    :post-condition: define alive correctly
    :return: a boolean: True if character is alive; False if character is not alive

    >>> alive_player = make_character()
    >>> test_alive_player = is_alive(alive_player)
    >>> test_alive_player
    True

    >>> dead_player = make_character()
    >>> dead_player["Current HP"] = 0
    >>> test_dead_player = is_alive(dead_player)
    >>> test_dead_player
    False

    """
    if character["Current HP"] <= 0:
        return False
    else:
        return True


def game() -> None:
    """
    Runs the game.
    """
    rows = 5
    columns = 5
    board = make_board(rows, columns)
    print(f"Welcome to the game!\nYou need to move to row {rows}, column {columns} to win!\n")
    character = make_character()
    achieved_goal = False
    while not achieved_goal and is_alive(character):
        describe_current_location(board, character)
        direction = get_user_choice()
        valid_move = validate_move(character, direction)
        if valid_move:
            move_character(character, direction)
            there_is_a_challenger = check_for_foes()
            if there_is_a_challenger:
                guessing_game(character, 4)
            achieved_goal = check_if_goal_attained(character)
        else:
            print(f"That's not a valid move. Please try again!\n")
    if not is_alive(character):
        print("You lost the game!")


def main():
    """
    Drives the program.
    """
    # greeting = tk.Entry(fg="yellow", bg="blue", width=50)

    # window = tk.Tk(greeting)

    # greeting.pack()
    game()


if __name__ == "__main__":
    main()
